### ISSUE TITLE
Missing cron for harvester run

### ISSUE THREAD

**Issue by etj** [geosolutions-it/dati-ckan-docker#4]
As documented in 
https://demo.geo-solutions.it/share/opendatanetwork/doc/online/install/ckan/install_ext_harvester.html#periodic-harvesting

there is need to run every 15 minutes the command:

    paster --plugin=ckanext-harvest harvester run     --config=/etc/ckan/default/ckan.ini

**Comment by randomorder** [comment]
Currently there is no CRON installed in the container. Scheduling periodic jobs in containers is often achieved in other ways depending on how the containers are deployed.
Would probably be a good idea to ask the client how they are currently doing it and see if we can use the same approach here

**Comment by randomorder** [comment]
One way to achieve this is to run a **docker exec** command in CRON on the host machine

**Comment by randomorder** [comment]
See https://github.com/geosolutions-it/dati-ckan-docker/commit/3d761e668cea6950888831ea6ac69695c6c297a2

**Comment by randomorder** [comment]
Example of usage will be documented

**Comment by randomorder** [comment]
See https://github.com/geosolutions-it/dati-ckan-docker/blob/docker-devel/README.md
